import {
	project1_1,
	project1_2,
	project1_3,
	project2_1,
	project2_2,
	project3_1,
	project3_2,
	project3_3,
	project3_4,
	project4_1,
	project5_1,
	project5_2,
	project5_3,
	project5_4,
	project6_1,
	project6_2,
	project6_3,
	project6_4,
	project6_5,
	project7_1,
	project7_2,
	project7_3,
} from '../../assets/projects';

const data = [
	{
		id: 1,
		title: 'TODO LIST APP',
		img_src: [project1_1, project1_2, project1_3],
		desc: '/sldkf',
		tools: ['css', 'html'],
		demoLink: 'https://todoapp-hatem.vercel.app/',
		gitLink: 'https://github.com/hatemhos11/ToDo-App',
	},
	{
		id: 2,
		title: 'MARVEL FOOTBALL ACADEMY',
		img_src: [project2_1, project2_2],
		desc: '',
		tools: ['css', 'html', 'Next.js', 'React.js', 'tailwindCSS'],
		demoLink: 'https://www.marvelfootballacademy.com/',
		gitLink: 'https://github.com/hatemhos11/Football_Academy',
	},
	{
		id: 3,
		title: 'WOULD YOU RATHER APP',
		img_src: [project3_1, project3_2, project3_3, project3_4],
		desc: '',
		tools: ['css', 'html', 'React.js', 'Redux', 'react-router_V5'],
		demoLink: 'https://wd-u-rather.netlify.app',
		gitLink:
			'https://github.com/hatemhos11/Would-You-Rather-Project---Udacity',
	},
	{
		id: 4,
		title: 'WEATHER APP',
		img_src: [project4_1],
		desc: '',
		tools: ['css', 'html'],
		demoLink: 'https://hatemhos11.github.io/weather-app/',
		gitLink: 'https://github.com/hatemhos11/weather-app',
	},
	{
		id: 5,
		title: 'LANDING PAGE',
		img_src: [project5_1, project5_2, project5_3, project5_4],
		desc: '',
		tools: ['css', 'html'],
		demoLink: 'https://hatemhos11.github.io/Landing-Page-1/',
		gitLink: 'https://github.com/hatemhos11/Blogr-landing-page',
	},
	{
		id: 6,
		title: 'Delivery App',
		img_src: [project6_1, project6_2, project6_3, project6_4, project6_5],
		desc: '',
		tools: ['css', 'html'],
		demoLink: 'https://hatemhos11.github.io/Delivery-project/',
		gitLink: 'https://github.com/hatemhos11/Delivery-project',
	},
];

export default data;
